COMPOSE := docker compose -f deploy/docker-compose.yml

.PHONY: help up infra down seed test logs colima-start colima-stop fmt proto proto-python deploy-web

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

colima-start: ## Start a capped, cool-running container VM (macOS)
	colima start --cpu 4 --memory 6

colima-stop: ## Stop the container VM and reclaim CPU/RAM
	colima stop

infra: ## Start backing services only (Postgres, Redis, Kafka)
	$(COMPOSE) up -d postgres redis kafka

up: ## Start the full stack (infra + services + Prometheus + Grafana)
	$(COMPOSE) up -d --build
	@echo ""
	@echo "  Dashboard → http://localhost:5173"
	@echo "  Gateway   → http://localhost:8080"
	@echo "  Grafana   → http://localhost:3000"
	@echo "  Prometheus→ http://localhost:9090"

down: ## Stop everything (volumes are kept; use 'down -v' to wipe data)
	$(COMPOSE) down

logs: ## Tail logs from all services
	$(COMPOSE) logs -f

proto: ## Regenerate Go gRPC stubs from proto/ (Java stubs are generated by Gradle at build time)
	@command -v protoc >/dev/null || { echo "protoc not found — install it (brew install protobuf)"; exit 1; }
	@command -v protoc-gen-go >/dev/null || go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	@command -v protoc-gen-go-grpc >/dev/null || go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
	protoc -I proto \
	  --go_out=gateway --go_opt=module=github.com/itsharsh007/openexchange/gateway \
	  --go-grpc_out=gateway --go-grpc_opt=module=github.com/itsharsh007/openexchange/gateway \
	  proto/openexchange.proto
	@echo "generated gateway/genproto/*.pb.go"

proto-python: ## Regenerate the risk service's Python protobuf stubs from proto/
	@command -v protoc >/dev/null || { echo "protoc not found — install it (brew install protobuf)"; exit 1; }
	@mkdir -p risk/app/genproto
	@touch risk/app/genproto/__init__.py
	protoc -I proto --python_out=risk/app/genproto proto/openexchange.proto
	@echo "generated risk/app/genproto/openexchange_pb2.py"

seed: ## Create demo accounts/symbols and simulated order flow
	./scripts/seed.sh

test: ## Run every service's test suite
	cd engine && ./gradlew test
	cd gateway && go test ./...
	cd risk && pytest -q
	cd web && npm test --silent

loadtest: ## Load test the gateway (read + write paths) — records throughput/latency
	./scripts/loadtest.sh

chaostest: ## Resilience test — kill the engine mid-flight, prove graceful degrade + recovery
	./scripts/chaostest.sh

deploy-web: ## Build and push web to GitHub Pages (set VITE_API_BASE + VITE_WS_URL first)
	cd web && npm ci && \
	VITE_API_BASE=$(VITE_API_BASE) VITE_WS_URL=$(VITE_WS_URL) npm run build
	@echo "Upload web/dist to GitHub Pages (or push to main to trigger the workflow)"

fmt: ## Format code in every service
	cd engine && ./gradlew spotlessApply || true
	cd gateway && go fmt ./...
	cd risk && ruff format . || true
	cd web && npm run format || true
