// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.1
// source: openexchange.proto

package oepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Enums ──────────────────────────────────────────────────────────────────
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_BUY              Side = 1
	Side_SELL             Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "BUY",
		2: "SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"BUY":              1,
		"SELL":             2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_openexchange_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_openexchange_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_LIMIT                  OrderType = 1
	OrderType_MARKET                 OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "LIMIT",
		2: "MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"LIMIT":                  1,
		"MARKET":                 2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_openexchange_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_openexchange_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{1}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ACCEPTED                 OrderStatus = 1
	OrderStatus_PARTIALLY_FILLED         OrderStatus = 2
	OrderStatus_FILLED                   OrderStatus = 3
	OrderStatus_CANCELLED                OrderStatus = 4
	OrderStatus_REJECTED                 OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ACCEPTED",
		2: "PARTIALLY_FILLED",
		3: "FILLED",
		4: "CANCELLED",
		5: "REJECTED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ACCEPTED":                 1,
		"PARTIALLY_FILLED":         2,
		"FILLED":                   3,
		"CANCELLED":                4,
		"REJECTED":                 5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openexchange_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_openexchange_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{2}
}

// ── Risk / ML signals ────────────────────────────────────────────────────────
// Published by the Python risk service to the `risk-signals` topic and surfaced
// in the dashboard's RiskPanel. The gateway may reject orders on a REJECT action.
type SignalKind int32

const (
	SignalKind_SIGNAL_KIND_UNSPECIFIED SignalKind = 0
	SignalKind_ANOMALY                 SignalKind = 1 // unusual order pattern (isolation forest)
	SignalKind_RISK_EXPOSURE           SignalKind = 2 // account exposure vs limits
	SignalKind_PRICE_PREDICTION        SignalKind = 3 // short-horizon price-direction forecast
)

// Enum value maps for SignalKind.
var (
	SignalKind_name = map[int32]string{
		0: "SIGNAL_KIND_UNSPECIFIED",
		1: "ANOMALY",
		2: "RISK_EXPOSURE",
		3: "PRICE_PREDICTION",
	}
	SignalKind_value = map[string]int32{
		"SIGNAL_KIND_UNSPECIFIED": 0,
		"ANOMALY":                 1,
		"RISK_EXPOSURE":           2,
		"PRICE_PREDICTION":        3,
	}
)

func (x SignalKind) Enum() *SignalKind {
	p := new(SignalKind)
	*p = x
	return p
}

func (x SignalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_openexchange_proto_enumTypes[3].Descriptor()
}

func (SignalKind) Type() protoreflect.EnumType {
	return &file_openexchange_proto_enumTypes[3]
}

func (x SignalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalKind.Descriptor instead.
func (SignalKind) EnumDescriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{3}
}

type SignalAction int32

const (
	SignalAction_SIGNAL_ACTION_UNSPECIFIED SignalAction = 0
	SignalAction_ALLOW                     SignalAction = 1
	SignalAction_REJECT                    SignalAction = 2
)

// Enum value maps for SignalAction.
var (
	SignalAction_name = map[int32]string{
		0: "SIGNAL_ACTION_UNSPECIFIED",
		1: "ALLOW",
		2: "REJECT",
	}
	SignalAction_value = map[string]int32{
		"SIGNAL_ACTION_UNSPECIFIED": 0,
		"ALLOW":                     1,
		"REJECT":                    2,
	}
)

func (x SignalAction) Enum() *SignalAction {
	p := new(SignalAction)
	*p = x
	return p
}

func (x SignalAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalAction) Descriptor() protoreflect.EnumDescriptor {
	return file_openexchange_proto_enumTypes[4].Descriptor()
}

func (SignalAction) Type() protoreflect.EnumType {
	return &file_openexchange_proto_enumTypes[4]
}

func (x SignalAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalAction.Descriptor instead.
func (SignalAction) EnumDescriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{4}
}

// ── Core messages ────────────────────────────────────────────────────────────
// Prices are integer ticks (e.g. cents) to avoid floating-point money bugs.
type NewOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientOrderId string                 `protobuf:"bytes,1,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"` // idempotency key supplied by the client
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=openexchange.v1.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=openexchange.v1.OrderType" json:"type,omitempty"`
	PriceTicks    int64                  `protobuf:"varint,6,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"` // ignored for MARKET orders
	Quantity      int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewOrder) Reset() {
	*x = NewOrder{}
	mi := &file_openexchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrder) ProtoMessage() {}

func (x *NewOrder) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrder.ProtoReflect.Descriptor instead.
func (*NewOrder) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{0}
}

func (x *NewOrder) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *NewOrder) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *NewOrder) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *NewOrder) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *NewOrder) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *NewOrder) GetPriceTicks() int64 {
	if x != nil {
		return x.PriceTicks
	}
	return 0
}

func (x *NewOrder) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Named *Request (not CancelOrder) so the message type does not collide with the RPC method
// name CancelOrder below — protoc rejects a method whose name shadows a message in scope.
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_openexchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type OrderAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status         OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=openexchange.v1.OrderStatus" json:"status,omitempty"`
	FilledQuantity int64                  `protobuf:"varint,3,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // populated on REJECTED
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderAck) Reset() {
	*x = OrderAck{}
	mi := &file_openexchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAck) ProtoMessage() {}

func (x *OrderAck) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAck.ProtoReflect.Descriptor instead.
func (*OrderAck) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{2}
}

func (x *OrderAck) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderAck) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderAck) GetFilledQuantity() int64 {
	if x != nil {
		return x.FilledQuantity
	}
	return 0
}

func (x *OrderAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PriceTicks    int64                  `protobuf:"varint,3,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	BuyOrderId    string                 `protobuf:"bytes,5,opt,name=buy_order_id,json=buyOrderId,proto3" json:"buy_order_id,omitempty"`
	SellOrderId   string                 `protobuf:"bytes,6,opt,name=sell_order_id,json=sellOrderId,proto3" json:"sell_order_id,omitempty"`
	TsMillis      int64                  `protobuf:"varint,7,opt,name=ts_millis,json=tsMillis,proto3" json:"ts_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_openexchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPriceTicks() int64 {
	if x != nil {
		return x.PriceTicks
	}
	return 0
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetBuyOrderId() string {
	if x != nil {
		return x.BuyOrderId
	}
	return ""
}

func (x *Trade) GetSellOrderId() string {
	if x != nil {
		return x.SellOrderId
	}
	return ""
}

func (x *Trade) GetTsMillis() int64 {
	if x != nil {
		return x.TsMillis
	}
	return 0
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceTicks    int64                  `protobuf:"varint,1,opt,name=price_ticks,json=priceTicks,proto3" json:"price_ticks,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_openexchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{4}
}

func (x *PriceLevel) GetPriceTicks() int64 {
	if x != nil {
		return x.PriceTicks
	}
	return 0
}

func (x *PriceLevel) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BookSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"` // best first (highest price)
	Asks          []*PriceLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"` // best first (lowest price)
	TsMillis      int64                  `protobuf:"varint,4,opt,name=ts_millis,json=tsMillis,proto3" json:"ts_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSnapshot) Reset() {
	*x = BookSnapshot{}
	mi := &file_openexchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSnapshot) ProtoMessage() {}

func (x *BookSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSnapshot.ProtoReflect.Descriptor instead.
func (*BookSnapshot) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{5}
}

func (x *BookSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BookSnapshot) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *BookSnapshot) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *BookSnapshot) GetTsMillis() int64 {
	if x != nil {
		return x.TsMillis
	}
	return 0
}

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_openexchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{6}
}

func (x *BookRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type RiskSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SignalKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=openexchange.v1.SignalKind" json:"kind,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`                                    // optional; empty for account-level signals
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                                    // 0..1 (anomaly/risk) or prob_up (prediction)
	Action        SignalAction           `protobuf:"varint,5,opt,name=action,proto3,enum=openexchange.v1.SignalAction" json:"action,omitempty"` // recommendation to the gateway
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                    // human-readable explanation
	TsMillis      int64                  `protobuf:"varint,7,opt,name=ts_millis,json=tsMillis,proto3" json:"ts_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskSignal) Reset() {
	*x = RiskSignal{}
	mi := &file_openexchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskSignal) ProtoMessage() {}

func (x *RiskSignal) ProtoReflect() protoreflect.Message {
	mi := &file_openexchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskSignal.ProtoReflect.Descriptor instead.
func (*RiskSignal) Descriptor() ([]byte, []int) {
	return file_openexchange_proto_rawDescGZIP(), []int{7}
}

func (x *RiskSignal) GetKind() SignalKind {
	if x != nil {
		return x.Kind
	}
	return SignalKind_SIGNAL_KIND_UNSPECIFIED
}

func (x *RiskSignal) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RiskSignal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RiskSignal) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RiskSignal) GetAction() SignalAction {
	if x != nil {
		return x.Action
	}
	return SignalAction_SIGNAL_ACTION_UNSPECIFIED
}

func (x *RiskSignal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RiskSignal) GetTsMillis() int64 {
	if x != nil {
		return x.TsMillis
	}
	return 0
}

var File_openexchange_proto protoreflect.FileDescriptor

const file_openexchange_proto_rawDesc = "" +
	"\n" +
	"\x12openexchange.proto\x12\x0fopenexchange.v1\"\x81\x02\n" +
	"\bNewOrder\x12&\n" +
	"\x0fclient_order_id\x18\x01 \x01(\tR\rclientOrderId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12)\n" +
	"\x04side\x18\x04 \x01(\x0e2\x15.openexchange.v1.SideR\x04side\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.openexchange.v1.OrderTypeR\x04type\x12\x1f\n" +
	"\vprice_ticks\x18\x06 \x01(\x03R\n" +
	"priceTicks\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\"f\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"\x9c\x01\n" +
	"\bOrderAck\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.openexchange.v1.OrderStatusR\x06status\x12'\n" +
	"\x0ffilled_quantity\x18\x03 \x01(\x03R\x0efilledQuantity\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xda\x01\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vprice_ticks\x18\x03 \x01(\x03R\n" +
	"priceTicks\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12 \n" +
	"\fbuy_order_id\x18\x05 \x01(\tR\n" +
	"buyOrderId\x12\"\n" +
	"\rsell_order_id\x18\x06 \x01(\tR\vsellOrderId\x12\x1b\n" +
	"\tts_millis\x18\a \x01(\x03R\btsMillis\"I\n" +
	"\n" +
	"PriceLevel\x12\x1f\n" +
	"\vprice_ticks\x18\x01 \x01(\x03R\n" +
	"priceTicks\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\xa5\x01\n" +
	"\fBookSnapshot\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12/\n" +
	"\x04bids\x18\x02 \x03(\v2\x1b.openexchange.v1.PriceLevelR\x04bids\x12/\n" +
	"\x04asks\x18\x03 \x03(\v2\x1b.openexchange.v1.PriceLevelR\x04asks\x12\x1b\n" +
	"\tts_millis\x18\x04 \x01(\x03R\btsMillis\";\n" +
	"\vBookRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\xf6\x01\n" +
	"\n" +
	"RiskSignal\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.openexchange.v1.SignalKindR\x04kind\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x125\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1d.openexchange.v1.SignalActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1b\n" +
	"\tts_millis\x18\a \x01(\x03R\btsMillis*/\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02*>\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\n" +
	"\n" +
	"\x06MARKET\x10\x02*x\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\x14\n" +
	"\x10PARTIALLY_FILLED\x10\x02\x12\n" +
	"\n" +
	"\x06FILLED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\f\n" +
	"\bREJECTED\x10\x05*_\n" +
	"\n" +
	"SignalKind\x12\x1b\n" +
	"\x17SIGNAL_KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aANOMALY\x10\x01\x12\x11\n" +
	"\rRISK_EXPOSURE\x10\x02\x12\x14\n" +
	"\x10PRICE_PREDICTION\x10\x03*D\n" +
	"\fSignalAction\x12\x1d\n" +
	"\x19SIGNAL_ACTION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\n" +
	"\n" +
	"\x06REJECT\x10\x022\xec\x01\n" +
	"\x0eMatchingEngine\x12C\n" +
	"\vSubmitOrder\x12\x19.openexchange.v1.NewOrder\x1a\x19.openexchange.v1.OrderAck\x12M\n" +
	"\vCancelOrder\x12#.openexchange.v1.CancelOrderRequest\x1a\x19.openexchange.v1.OrderAck\x12F\n" +
	"\aGetBook\x12\x1c.openexchange.v1.BookRequest\x1a\x1d.openexchange.v1.BookSnapshotBU\n" +
	"\x16com.openexchange.protoP\x01Z9github.com/itsharsh007/openexchange/gateway/genproto;oepbb\x06proto3"

var (
	file_openexchange_proto_rawDescOnce sync.Once
	file_openexchange_proto_rawDescData []byte
)

func file_openexchange_proto_rawDescGZIP() []byte {
	file_openexchange_proto_rawDescOnce.Do(func() {
		file_openexchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openexchange_proto_rawDesc), len(file_openexchange_proto_rawDesc)))
	})
	return file_openexchange_proto_rawDescData
}

var file_openexchange_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openexchange_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_openexchange_proto_goTypes = []any{
	(Side)(0),                  // 0: openexchange.v1.Side
	(OrderType)(0),             // 1: openexchange.v1.OrderType
	(OrderStatus)(0),           // 2: openexchange.v1.OrderStatus
	(SignalKind)(0),            // 3: openexchange.v1.SignalKind
	(SignalAction)(0),          // 4: openexchange.v1.SignalAction
	(*NewOrder)(nil),           // 5: openexchange.v1.NewOrder
	(*CancelOrderRequest)(nil), // 6: openexchange.v1.CancelOrderRequest
	(*OrderAck)(nil),           // 7: openexchange.v1.OrderAck
	(*Trade)(nil),              // 8: openexchange.v1.Trade
	(*PriceLevel)(nil),         // 9: openexchange.v1.PriceLevel
	(*BookSnapshot)(nil),       // 10: openexchange.v1.BookSnapshot
	(*BookRequest)(nil),        // 11: openexchange.v1.BookRequest
	(*RiskSignal)(nil),         // 12: openexchange.v1.RiskSignal
}
var file_openexchange_proto_depIdxs = []int32{
	0,  // 0: openexchange.v1.NewOrder.side:type_name -> openexchange.v1.Side
	1,  // 1: openexchange.v1.NewOrder.type:type_name -> openexchange.v1.OrderType
	2,  // 2: openexchange.v1.OrderAck.status:type_name -> openexchange.v1.OrderStatus
	9,  // 3: openexchange.v1.BookSnapshot.bids:type_name -> openexchange.v1.PriceLevel
	9,  // 4: openexchange.v1.BookSnapshot.asks:type_name -> openexchange.v1.PriceLevel
	3,  // 5: openexchange.v1.RiskSignal.kind:type_name -> openexchange.v1.SignalKind
	4,  // 6: openexchange.v1.RiskSignal.action:type_name -> openexchange.v1.SignalAction
	5,  // 7: openexchange.v1.MatchingEngine.SubmitOrder:input_type -> openexchange.v1.NewOrder
	6,  // 8: openexchange.v1.MatchingEngine.CancelOrder:input_type -> openexchange.v1.CancelOrderRequest
	11, // 9: openexchange.v1.MatchingEngine.GetBook:input_type -> openexchange.v1.BookRequest
	7,  // 10: openexchange.v1.MatchingEngine.SubmitOrder:output_type -> openexchange.v1.OrderAck
	7,  // 11: openexchange.v1.MatchingEngine.CancelOrder:output_type -> openexchange.v1.OrderAck
	10, // 12: openexchange.v1.MatchingEngine.GetBook:output_type -> openexchange.v1.BookSnapshot
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_openexchange_proto_init() }
func file_openexchange_proto_init() {
	if File_openexchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openexchange_proto_rawDesc), len(file_openexchange_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openexchange_proto_goTypes,
		DependencyIndexes: file_openexchange_proto_depIdxs,
		EnumInfos:         file_openexchange_proto_enumTypes,
		MessageInfos:      file_openexchange_proto_msgTypes,
	}.Build()
	File_openexchange_proto = out.File
	file_openexchange_proto_goTypes = nil
	file_openexchange_proto_depIdxs = nil
}
